version: '3'

vars:
  ver_path: .github/VERSION
  ver:
    sh: cat '{{ .ver_path }}'
  dist_dir: 'shath-yar-{{ .ver }}'
  zip_name: '{{ .dist_dir }}.zip'
  repo_owner: Illbjorn
  repo_name: shath-yar

tasks:
  version:
    aliases: [v]
    desc: Outputs the current Shath'yar version.
    silent: true
    interactive: true
    cmd: echo '{{ .ver }}'

  # Task: Bump
  #
  # >> Examples
  #     $ task bump
  #     Incrementing version ['0.1.4']=>['0.1.5'].
  #
  #     $ task bump s=minor
  #     Incrementing version ['0.1.4']=>['0.2.0'].
  #
  #     $ task bump s=major
  #     Incrementing version ['0.1.4']=>['1.0.0'].
  #
  bump:
    aliases: [b]
    desc: Bumps the provided segment of the semver string at {{ .ver_path }}.
    vars:
      segment: '{{ if .s }}{{ .s }}{{ else }}patch{{ end }}'
    cmd: ver_path='{{ .ver_path }}' segment='{{ .segment }}' .github/scripts/bump.sh

  create-git-tag:
    internal: true
    cmd: git tag '{{ .tag }}'

  push-tag-ref:
    internal: true
    cmd: git push origin '{{ .tag }}'

  create-tagged-release:
    desc: Creates a Git tag from '{{ .ver_path }}' and pushes to that ref.
    vars:
      tag: 'v{{ .ver }}'
    cmds:
      - task: create-git-tag
        vars:
          tag: '{{ .tag }}'
      - task: push-tag-ref
        vars:
          tag: '{{ .tag }}'

  create-release-file:
    desc: Creates the zipped release file to attach to the GitHub release.
    cmds:
      - cmd: rm -rf *.zip
      - cmd: mkdir '{{ .dist_dir }}'
      - defer: rm -rf '{{ .dist_dir }}'
      - cmd: cp ShathYar.lua '{{ .dist_dir }}'
      - cmd: cp ShathYar.toc '{{ .dist_dir }}'
      - cmd: cp ShathYar.xml '{{ .dist_dir }}'
      - cmd: cp LICENSE '{{ .dist_dir }}'
      - cmd: zip -r '{{ .zip_name }}' '{{ .dist_dir }}'

  create-release:
    aliases: [cr]
    desc: Creates a GitHub release.
    preconditions:
      - sh: '[[ -n "{{ .tag }}" ]]'
        msg: A 'tag' input value is required.
      - sh: '[[ -n "{{ .title }}" ]]'
        msg: A 'title' input value is required.
    env:
      tag: '{{ .tag }}'
      title: '{{ .title }}'
      body: '{{ .body }}'
      files: '{{ .zip_name }}'
      repo_owner: '{{ .repo_owner }}'
      repo_name: '{{ .repo_name }}'
    cmds:
      - task: create-release-file
      - cmd: .github/scripts/create-release.sh
