name: On Merge to Main

on:
  push:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

jobs:
  release:
    name: Create Release
    runs-on: [ubuntu-latest]
    permissions:
      # Required to create the release.
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          fetch-tags: true

      - name: Set up Task
        uses: illbjorn/setup-task@main

      - name: Create the GitHub Release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          base="$(git show-ref --tags | head -1 | awk '{print $1}')"
          head="${{ github.sha }}"
          task cghr \
            tag="v$(task v)" \
            title="Shath'yar Release: $(task v)" \
            body="$(task rn s="${base}" e="${head}")"
